
- name: Unarchive a tomcat tar from tomcat website
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.14/bin/apache-tomcat-10.0.14.tar.gz
    dest: /etc/
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
   - tar-copy

- name: create a soft link to th tomcat folder
  file:
    src: /etc/apache-tomcat-10.0.14
    dest: /etc/tomcat
    owner: root
    group: root
    state: link
  tags:
   - softlink

- name: Copy file with owner and permissions
  copy:
    src: files/tomcat-users.xml
    dest: /etc/tomcat/conf/tomcat-users.xml
    owner: root
    group: root
    mode: '0644'

- name: Copy context.xml file with owner and permissions
  copy:
    src: files/context.xml
    dest: /etc/tomcat/webapps/manager/META-INF/context.xml
    owner: root
    group: root
    mode: '0644'

